### PR TITLE
Feature logout

### PR DESCRIPTION
**Pull request by balmas**
This solution was taken from https://stackoverflow.com/questions/26080632/how-do-i-log-out-of-a-chrome-identity-oauth-provider

I'm not sure to what degree it's a hack and whether we want to offer it back to the creators of the library, but it does seem to work in Chrome.

### CODE REVIEW

**Review by kirlat — APPROVED** [review]
I'm wondering if we should use a "V2" logout URL of Auth0 (https://auth0.com/docs/logout) or maybe even a recommended by them redirection with a "returnTo" URL parameter. What do you think?

Here is also a discussion that might be related: https://community.auth0.com/t/log-out-doesnt-work-and-automatically-sign-in/14826/7

**Comment by kirlat** [comment]
I'm also wondering if we should merge it to a separate branch maybe as this is a deviation from what the forked repo was (or maybe not).

**Comment by balmas** [comment]
>I'm wondering if we should use a "V2" logout URL of Auth0 (https://auth0.com/docs/logout) or maybe even a recommended by them redirection with a "returnTo" URL parameter. What do you think?

That's a good catch re the V2 url. I didn't notice that.

Re the returnTo URL param, that can be specified in options, and I am supplying it in the webextension (currently it's being set in the auth environment file). I think that it should not be enforced in this method here, but supplied if needed, and it should be up to the client to specify it.

> I'm also wondering if we should merge it to a separate branch maybe as this is a deviation from what the forked repo was (or maybe not).

I don't know. I think we are going to need an auth library that can be used by all the applications, to make sure we have consistent behaviors across them all. But that shouldn't be here. I think however that this feature is one that others could use and I wouldn't have a problem submitting it as a PR, but I need to document it better first.   I will make the change you suggest for the v2 url and add a little documentation and then we can decide if it stays in a branch or gets merged.

**Comment by kirlat** [comment]
> I don't know. I think we are going to need an auth library that can be used by all the applications, to make sure we have consistent behaviors across them all. But that shouldn't be here. I think however that this feature is one that others could use and I wouldn't have a problem submitting it as a PR, but I need to document it better first. I will make the change you suggest for the v2 url and add a little documentation and then we can decide if it stays in a branch or gets merged.

Agree. I just wanted to offer it for discussion so we would keep it as an option somewhere in the far corner of our minds 🙂 . We probably have to start using authentication workflow more to figure out what would be the best solution to satisfy both webextension and embedded lib requirements.

**Review by balmas — COMMENTED** [review]
this looks ok to me @kirlat . Can we merge this whole PR now do you think? I can't remember what we decided about this. We were waiting to see if your PR to the original code got accepted, I know. But other than that I don't know what our strategy is.

**Pull request closed without merging**
